# Python review

Goals:
- recall basic Python vocab
- practice markdown

## Libraries and packages

**library**: a collection of code that we use to perform specific tasks in our programs

**NumPy**:
- core library for numerical computing in Python 
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreviation** 

In [2]:
import numpy as np

## Variables

**variable**: a name we assign to a particular object in Python

Example:

In [3]:
# Assign a small array to a variable a
a = np.array([[1,1,2],[3,5,8]])

In [4]:
# Run cell with the variable name to show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [5]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object**: a bundle of properties and actions about something specific 

Example: 

Object: data frame
Properties: number rows, name of columns, date created
Actions: selecting specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use variable and object interchangebly 