# Python review

Goals:
- recall basic Python vocab
- practice markdown

## Libraries and packages

**library**: a collection of code that we use to perform specific tasks in our programs

**NumPy**:
- core library for numerical computing in Python 
- many other libraries use NumPy arrays as building blocks
- computations on NumPy are optimized for speed and memory usage

Let's import NumPy with **standard abbreviation** 

In [1]:
import numpy as np

## Variables

**variable**: a name we assign to a particular object in Python

Example:

In [2]:
# Assign a small array to a variable a
a = np.array([[1,1,2],[3,5,8]])

In [3]:
# Run cell with the variable name to show the value
a

array([[1, 1, 2],
       [3, 5, 8]])

In [4]:
# Use `print` function to print the value
print(a)

[[1 1 2]
 [3 5 8]]


## Objects

**object**: a bundle of properties and actions about something specific 

Example: 

Object: data frame
Properties: number rows, name of columns, date created
Actions: selecting specific row, adding a new column

A variable is the name we give a specific object, and the same object can be referenced by different variables.

In practice, we can often use variable and object interchangebly 

## Types

Every object in Python has a **type**. The type tells us what kind of object it is. 

We can also call the type of an object, the **class** of an object and they both mean what kind of object we have.

In [5]:
print(a)

# Check the type/class of variable/object by using `type` function
type(a)

[[1 1 2]
 [3 5 8]]


numpy.ndarray

In [10]:
# Access a number
print(a[0,0])
print(a[1,1])

1
5


In [8]:
# Check the type of an entry on the array by indexing
type(a[0,0])

numpy.int64

Notice that `type(a[0,0])` is `numpy.int64` and not just the standard Python integer type. This is telling us that 1 is an integer stored as a 64-bit number.

## Functions

`print` was our first example of a Python **function**.

Functions take in a set of **arguments** and those arguments create an **output**.

argument = parameter

We can ask information about a function by executing `?function`

In [11]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

This information is a **docstring**.

A function has two types of arguments:

- **nonoptional argument**: argument *you* need to specify for the function to do something
- **optional argument**: arguments that are pre-filled with a default value by the function. You can overrride them. Optional arguments appear inside the parenthesis in the form `optional_argument=default_value`

In [12]:
print('changing the default end argument', end = ':)')

changing the default end argument:)

## Attributes and methods

An object in Python has attributes and methods.

- **attribute**: a property of an object, some piece of information about it
- **method**: a procedure associated witht he object, an action where the main ingredient is the object

## Check-in

Fish attributes:

- length, color, species

Fish methods: 

- bite(), swim()

**Example**
Attributes for `numpy.arrays`

We can access a variable's attributes and methods by adding a period `.` at the end of the variable's name.

`variable.method()` or `variable.attribute`

In [13]:
a.shape

(2, 3)

In [14]:
type(a.shape)

tuple

In [15]:
# Methods examples
# min() returns the minimum value along a specified axis
a.min(axis = 0)

array([1, 1, 2])

## Check-in

We can also call the `min` method without any parameters:

In [16]:
a.min()

1

Remember: methods are funcitons associated with an object.

In [17]:
type(a.min)

builtin_function_or_method

## Exercise

1. Read the `print` function help. What is the type of the argument `sep`? Is this an optional or non-optional argument? Why?

2. Create two new variables, one with the integer value 77 and another one with the string 99. 

3. Use your variables to print `77%99%77` by changing the value of one of the optional arguments in `print`.

In [18]:
?print

Signature: print(*args, sep=' ', end='\n', file=None, flush=False)
Docstring:
Prints the values to a stream, or to sys.stdout by default.

sep
  string inserted between values, default a space.
end
  string appended after the last value, default a newline.
file
  a file-like object (stream); defaults to the current sys.stdout.
flush
  whether to forcibly flush the stream.
Type:      builtin_function_or_method

`sep` is an optional argument, it runs with the default space separater if not otherwise specified.

In [25]:
i = 77
s = '99'

print(i,s,i, sep = '%')

77%99%77
